### ISSUE TITLE
Can agg genotype extract non segregating sites

### ISSUE THREAD

**Issue by TsviyaOlender** [Illumina/agg#18]
Hi
I need to extract certain positions from gvcf files that are not segregating in the cohort. It is important for me to know weather these locations are reference allele call, or without sufficient coverage at the positions of interest.
Is there a way to make agg genotype do that?

Thanks
Tsviya

**Comment by jaredo** [comment]
You can take a look at the ".dpt" files that agg generates (use `bcftools view`), that will give you per-position conservative measures of depth and GQ for any region of the genome you are interested in.

This idea of genotyping arbitrary variants has come up before, but I have concerns about implementing it. A missing variant can be due to lack of sensitivity (particularly for indels) rather than the variant truly not being present.

**Comment by TsviyaOlender** [comment]
thanks
