### ISSUE TITLE
genotyping on specific samples

### ISSUE THREAD

**Issue by mwilkers** [Illumina/agg#24]
Thank you for this well done tool.

Is it possible to genotype on a restricted sample list from previously built chunks? This would enable one to re-use previously built chunks for cohort VCFs, rather than rebuild these every time because excluding samples after genotyping influences the construction of cohort VCF.

I see subset options commented out in agg_genotyper.cpp.  Is it possible to re-activate these options?  

Thank you,
Matt

**Comment by jaredo** [comment]
Hi Matt,

Thanks for your interest. As you noticed the subsetting functionality was planned but never actually implemented.  A simple and effective workaround is to pipe the agg output directly to stdout and then subset with bcftools:

```
agg genotype chunk1.bcf chunk2.bcf -Ou -o - |  bcftools view -i 'AC>0' -s NA12878,NA12877 -Ob -o subsetted.bcf
```
Note that this won't affect the genotyping of the samples since agg does not do any statistical inference of genotypes, it just populates the genotype calls with `DP`/`GQ` values that were extracted from the homozygous reference blocks in the original GVCF. I do have plans to implement a more correct genotyping model using likelihoods and a sensible prior, but won't have time in the near term.

cheers,

Jared

**Comment by mwilkers** [comment]
Thank you.  

I noticed that this method of sample restricting will not effect INFO tags, such as PF, which retain their original value from the whole cohort.  So this subset strategy does retain some information from the chunks from which it was built.  

Is there a way to subset and have the AGG INFO tags updated?  I could also see this being recalculated after the fact.


Matt

**Comment by jaredo** [comment]
>Is there a way to subset and have the AGG INFO tags updated? I could also see this being recalculated after the fact.

Certainly. We have a plugin called `update-info` under the (bcftools-plugins)[https://github.com/Illumina/agg/tree/master/bcftools_plugins] directory that can do this for you. Let me know if you have any problems with it.
